package com.raynet.eyepatch

import java.io.File
import kotlin.math.acos

/**
 * JVM harness: drives the REAL EyeModel3D (fit + predict + two-fold
 * disambiguation) through the synthetic look-around set generated by
 * sixdrepnet/3DeepVOG-main/tools/tier3_parity.py and checks:
 *
 *   - GAZE DIRECTION vs ground truth (the disambiguation correctness check; the
 *     forward/inverse pair recovers direction to machine precision, so any error
 *     here is a real bug — a flipped branch shows as ~180°, a wrong branch as a
 *     large angle while predictBoth still contains the correct one).
 *   - EYEBALL CENTRE / RADIUS as parity vs the reference numpy fit (intersect of
 *     the same unproject lines) — validates finishFit's composition + the port.
 *
 * Run via tools/tier3_parity/run.sh (compiles this with EyeGeometry.kt +
 * EyeModel3D.kt and passes the golden file path as argv[0]).
 */
private var failures = 0

private fun check(label: String, got: Double, exp: Double, tol: Double) {
    val d = kotlin.math.abs(got - exp)
    val ok = d <= tol
    if (!ok) failures++
    println("    %-26s got=%+.6g exp=%+.6g  |d|=%.3e  %s".format(label, got, exp, d, if (ok) "ok" else "FAIL"))
}

private fun angleDeg(u: EyeGeometry.V3, g: DoubleArray): Double {
    val un = u.normalized()
    val d = (un.x * g[0] + un.y * g[1] + un.z * g[2]).coerceIn(-1.0, 1.0)
    return Math.toDegrees(acos(d))
}

private class Ell(
    val cx: Double, val cy: Double, val w: Double, val h: Double, val rad: Double,
    val g: DoubleArray,
)

fun main(args: Array<String>) {
    val path = args.getOrNull(0) ?: error("usage: Tier3Check <tier3_golden.txt>")
    var focal = 1200.0; var cx0 = 160.0; var cy0 = 120.0; var assumedR = 40.0
    var truthEye = doubleArrayOf(0.0, 0.0, 0.0); var truthR = 0.0
    val ells = ArrayList<Ell>()
    File(path).readLines().forEach { line ->
        val t = line.trim().split(Regex("\\s+"))
        when (t.firstOrNull()) {
            "META" -> { focal = t[1].toDouble(); cx0 = t[2].toDouble(); cy0 = t[3].toDouble(); assumedR = t[4].toDouble() }
            "TRUTH" -> { truthEye = doubleArrayOf(t[1].toDouble(), t[2].toDouble(), t[3].toDouble()); truthR = t[4].toDouble() }
            "ELL" -> ells.add(Ell(t[1].toDouble(), t[2].toDouble(), t[3].toDouble(), t[4].toDouble(), t[5].toDouble(),
                doubleArrayOf(t[6].toDouble(), t[7].toDouble(), t[8].toDouble())))
        }
    }
    println("loaded ${ells.size} ellipses; focal=$focal pp=($cx0,$cy0) assumedR=$assumedR")

    val model = EyeModel3D(focalPx = focal, assumedPupilRadiusPx = assumedR, cx = cx0, cy = cy0)
    for (e in ells) model.accumulate(EyeModel3D.Ellipse(e.cx, e.cy, e.w, e.h, e.rad, 1.0))
    val ok = model.finishFit()
    println("\n=== FIT (vs synthetic ground truth) ===  fitCount=${model.fitCount} ok=$ok")
    val c = model.eyeCenter ?: error("finishFit failed")
    check("eyeCentre.x", c.x, truthEye[0], 1e-3)
    check("eyeCentre.y", c.y, truthEye[1], 1e-3)
    check("eyeCentre.z", c.z, truthEye[2], 1e-2)
    check("eyeRadiusPx", model.eyeRadiusPx, truthR, 1e-2)

    println("\n=== PREDICT (gaze direction vs GROUND TRUTH) ===")
    var bestSum = 0.0; var bestMax = 0.0
    var chosenSum = 0.0; var chosenMax = 0.0
    var disambigFails = 0; var nulls = 0
    for (e in ells) {
        val el = EyeModel3D.Ellipse(e.cx, e.cy, e.w, e.h, e.rad, 1.0)
        val both = model.predictBoth(el)
        val chosen = model.predict(el)
        if (both == null || chosen == null) { nulls++; continue }
        val aA = angleDeg(both.first.gaze, e.g); val aB = angleDeg(both.second.gaze, e.g)
        val best = minOf(aA, aB)
        val ch = angleDeg(chosen.gaze, e.g)
        bestSum += best; bestMax = maxOf(bestMax, best)
        chosenSum += ch; chosenMax = maxOf(chosenMax, ch)
        if (ch > best + 1.0) disambigFails++       // predict picked the worse branch
    }
    val n = ells.size - nulls
    println("    frames=%d nulls=%d".format(n, nulls))
    println("    best-branch angle  mean=%.4f° max=%.4f°  (geometry; should be ~0)".format(bestSum / n, bestMax))
    println("    chosen     angle   mean=%.4f° max=%.4f°  (disambiguation)".format(chosenSum / n, chosenMax))
    println("    disambiguation failures (chosen != best): %d / %d".format(disambigFails, n))
    if (bestMax > 0.5) { failures++; println("    FAIL: geometry — predictBoth never contains the true gaze") }
    if (disambigFails > 0) { failures++; println("    FAIL: two-fold disambiguation picks the wrong branch") }

    println("\n" + if (failures == 0) "ALL TIER-3 CHECKS PASSED"
                    else "TIER-3: $failures CHECK(S) FAILED")
    if (failures != 0) kotlin.system.exitProcess(1)
}
